wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1749215832.695004
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 76
      2:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      - 76
      3:
      - 7
      - 13
      - 23
      4: 3.8.10
      5: 0.15.5
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: loss val regression
      5: 1
      6:
      - 1
    - 1: loss val lv
      5: 1
      6:
      - 1
    - 1: loss val beta
      5: 1
      6:
      - 1
    - 1: loss val beta sig
      5: 1
      6:
      - 1
    - 1: loss val beta noise
      5: 1
      6:
      - 1
    - 1: loss val attractive
      5: 1
      6:
      - 1
    - 1: loss val repulsive
      5: 1
      6:
      - 1
    - 1: loss val repulsive 2
      5: 1
      6:
      - 1
    - 1: lr-Adam
      5: 1
      6:
      - 1
    - 1: loss regression
      5: 1
      6:
      - 1
    - 1: loss lv
      5: 1
      6:
      - 1
    - 1: loss beta
      5: 1
      6:
      - 1
    - 1: loss beta sig
      5: 1
      6:
      - 1
    - 1: loss beta noise
      5: 1
      6:
      - 1
    - 1: loss attractive
      5: 1
      6:
      - 1
    - 1: loss repulsive
      5: 1
      6:
      - 1
    - 1: loss repulsive 2
      5: 1
      6:
      - 1
